# Generated by Django 4.1.7 on 2023-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('companyName', models.CharField(max_length=100)),
                ('lastContacted', models.DateField()),
                ('person', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('personTitle', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('usState', models.CharField(max_length=100)),
            ],
        ),
    ]
