# Generated by Django 4.1.7 on 2023-02-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
